apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
  labels:
    app: postgres
data:
  POSTGRES_DB: flask-db
  POSTGRES_USER: flask-user
  POSTGRES_PASSWORD: flask-password
